"use client";
import { useState, type FormEvent } from "react";
import { toast } from "sonner";
import { authHeaders, requireLogin, type User } from "@/lib/auth";
import { API_URL } from "@/lib/api";
import type { Post } from "@/lib/types";
export function CommunityPanel({projectId,posts,me,onChanged}:{projectId:number;posts:Post[];me:User|null;onChanged:()=>Promise<void>}){
 const [content,setContent]=useState(""); const [editingId,setEditingId]=useState<number|null>(null); const [editingContent,setEditingContent]=useState("");
 async function createPost(e:FormEvent){e.preventDefault(); try{await requireLogin(); const r=await fetch(`${API_URL}/projects/${projectId}/posts`,{method:"POST",headers:{"Content-Type":"application/json",...authHeaders()},body:JSON.stringify({content})}); if(!r.ok) throw new Error(await r.text()); setContent(""); toast.success("게시글이 등록되었습니다."); await onChanged();}catch(e:any){toast.error(e?.message||"게시글 작성 실패")}}
 async function updatePost(id:number){try{const r=await fetch(`${API_URL}/posts/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json",...authHeaders()},body:JSON.stringify({content:editingContent})}); if(!r.ok) throw new Error(await r.text()); setEditingId(null); setEditingContent(""); toast.success("게시글이 수정되었습니다."); await onChanged();}catch(e:any){toast.error(e?.message||"게시글 수정 실패")}}
 async function deletePost(id:number){if(!confirm("게시글을 삭제하시겠습니까?"))return; try{const r=await fetch(`${API_URL}/posts/${id}`,{method:"DELETE",headers:authHeaders()}); if(!r.ok) throw new Error(await r.text()); toast.success("게시글이 삭제되었습니다."); await onChanged();}catch(e:any){toast.error(e?.message||"게시글 삭제 실패")}}
 return <section className="panel"><div className="sectionHeader compact"><div><p className="eyebrow small">Community</p><h2>커뮤니티</h2></div></div>{me?<form className="postForm" onSubmit={createPost}><textarea className="textarea" value={content} onChange={e=>setContent(e.target.value)} placeholder="질문이나 의견을 남겨보세요." required/><button className="secondaryButton" type="submit">게시글 등록</button></form>:<div className="empty">글을 작성하려면 SNS 로그인이 필요합니다.</div>}<div className="posts">{posts.map(p=><div className="post" key={p.id}><div className="postTop"><div><strong>{p.user?.name||"회원"}</strong><p className="meta">{new Date(p.createdAt).toLocaleString()}</p></div>{me?.id===p.userId&&<div className="miniActions"><button className="miniButton" onClick={()=>{setEditingId(p.id);setEditingContent(p.content)}}>수정</button><button className="miniDangerButton" onClick={()=>deletePost(p.id)}>삭제</button></div>}</div>{editingId===p.id?<div className="editBox"><textarea className="textarea" value={editingContent} onChange={e=>setEditingContent(e.target.value)}/><button className="secondaryButton" onClick={()=>updatePost(p.id)}>저장</button></div>:<p>{p.content}</p>}</div>)}</div></section>;
}
